export default {
    ACCOUNT_SIGN_IN:   'ACCOUNT_SIGN_IN',
    ACCOUNT_SIGN_OUT:  'ACCOUNT_SIGN_OUT',
    USER_CREATED:      'USER_CREATED',
    USER_CONVERSATIONS:'USER_CONVERSATIONS',
    GET_USER_BY_USERNAME: 'GET_USER_BY_USERNAME',
    GET_USER_BY_ID: 'GET_USER_BY_ID',
    GET_USERS: 'GET_USERS',
    MODIFY_USER: 'MODIFY_USER',
    GET_THREADS_IN_CONVERSATION: 'GET_THREADS_IN_CONVERSATION',
    GET_GROUPS: 'GET_GROUPS',
    GET_ALL_GROUPS: 'GET_ALL_GROUPS',
    GET_MESSAGES_IN_CONVERSATION: 'GET_MESSAGES_IN_CONVERSATION',
    GET_MESSAGES_IN_THREAD: 'GET_MESSAGES_IN_THREAD',
    GET_GROUP_USERS: 'GET_GROUP_USERS',
    INSERT_NEW_MESSAGE: 'INSERT_NEW_MESSAGE',
    UPDATE_USER: 'UPDATE_USER',
    GET_GROUP_CONVERSATIONS:'GET_GROUP_CONVERSATIONS',
    CREATE_GROUP: 'CREATE_GROUP',


    LANGUAGES: [
        "English",
        "Arabic",
        "Chinese",
        "Czech",
        "Dutch",
        "French",
        "German",
        "Gujarati",
        "Hindi",
        "Latin",
        "Korean",
        "Spanish",
        "Urdu"
    ]
}

