export default {
    ACCOUNT_SIGN_IN:   'ACCOUNT_SIGN_IN',
    ACCOUNT_SIGN_OUT:  'ACCOUNT_SIGN_OUT',
    USER_CREATED:      'USER_CREATED',
    USER_CONVERSATIONS:'USER_CONVERSATIONS',
    GET_USER_BY_USERNAME: 'GET_USER_BY_USERNAME',
    GET_USER_BY_ID: 'GET_USER_BY_ID',
    GET_USERS: 'GET_USERS',
    GET_THREADS_IN_CONVERSATION: 'GET_THREADS_IN_CONVERSATION'
}